### ISSUE TITLE
A checklist for the documentation pages

### ISSUE THREAD

**Issue by wehs7661** [wehs7661/ensemble_md#2]
- [x] Get passed the documentation building 
- [x] Describe how $\Delta$ in the acceptance ratio is calculated
- [x] Describe how swaps should be proposed
- [x] Describe how concurrent multiple swaps should be carried out and the math behind it
- [x] Describe whether the weights are combined across the replicas to be swapped or across all possible replicas
- [x] Modify the description of specifying input files to reflect the fact that multiple GROMACS input files can be used.
- [x] Add the description that fixing the distance reference does not work for multiple input GRO files (and it doesn't make sense for it to work for multiple GRO files)
- [x] Add a section about what MDP parameters are recommended (e.g. nstlog should be less or equal to nst_sim in YAML)

**Comment by wehs7661** [comment]
Most action items have been finished, so I am closing the issue now. The remaining and follow-up work will be addressed in issue #26.
