### ISSUE TITLE
A checklist for docstring proofreading

### ISSUE THREAD

**Issue by wehs7661** [wehs7661/ensemble_md#43]
As a part of issue #41, here is a checklist for keeping track of the progress of proofreading docstrings of all modules in `ensemble_md`. 
- [x] `replica_exchange_EE.py`
- [x] `utils`
  - [x] `exceptions.py`
  - [x] `gmx_parser.py`
  - [x] `utils.py`
- [x] `analysis`
  - [x] `analyze_traj.py`
  - [x] `analyze_matrix.py`
  - [x] `analyze_free_energy.py`
  - [x] `clustering.py`
  - [x] `synthesize_data.py`
  - [x] `msm_analysis.py`
- [x] `cli`
  - [x] `explore_REXEE.py`

**Comment by wehs7661** [comment]
Closing the issue as this has been addressed by PR #48.
